ARG GO_BUILD_IMAGE=golang:1.26-alpine
ARG ALPINE_IMAGE=alpine:3.22
ARG GO_PROXY=https://proxy.golang.org,direct

FROM ${GO_BUILD_IMAGE} AS build

ARG GO_PROXY
WORKDIR /src
COPY server/go.mod server/go.sum* ./
RUN GOPROXY=${GO_PROXY} go mod download
COPY server/ ./
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/repomender ./cmd/repomender

FROM ${ALPINE_IMAGE}

COPY --from=build /out/repomender /usr/local/bin/repomender
USER 65532:65532
ENTRYPOINT ["repomender"]
