package metrics

import (
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

// The standard library HTTP and synchronization packages provide a small,
// dependency-free Prometheus exposition surface. This keeps metrics available
// in minimal containers while allowing any Prometheus-compatible collector to
// scrape the same stable endpoint.

type key struct {
	method string
	route  string
	status string
}

type sample struct {
	count uint64
	sum   time.Duration
}

// Registry stores bounded-cardinality request samples. Routes come from the
// Go ServeMux pattern when available, so user-controlled IDs never become
// unbounded Prometheus labels.
type Registry struct {
	mu                sync.Mutex
	requests          map[key]sample
	build             string
	rateLimitRejected uint64
}

func New(serviceVersion string) *Registry {
	return &Registry{requests: make(map[key]sample), build: sanitizeLabel(serviceVersion)}
}

func (r *Registry) Record(method, route string, status int, elapsed time.Duration) {
	if r == nil {
		return
	}
	if route == "" {
		route = "unknown"
	}
	statusClass := strconv.Itoa(status/100) + "xx"
	r.mu.Lock()
	item := r.requests[key{method: method, route: route, status: statusClass}]
	item.count++
	item.sum += elapsed
	r.requests[key{method: method, route: route, status: statusClass}] = item
	r.mu.Unlock()
}

func (r *Registry) RecordRateLimitRejection() {
	if r == nil {
		return
	}
	r.mu.Lock()
	r.rateLimitRejected++
	r.mu.Unlock()
}

// Middleware records every response, including failures generated by the
// rate-limit layer, without changing the handler's streaming behavior.
func (r *Registry) Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		started := time.Now()
		wrapped := &responseWriter{ResponseWriter: w}
		next.ServeHTTP(wrapped, req)
		route := req.Pattern
		if route == "" {
			route = normalizedPath(req.URL.Path)
		}
		r.Record(req.Method, route, wrapped.status, time.Since(started))
	})
}

func (r *Registry) Handler(metricsToken string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if metricsToken != "" && req.Header.Get("Authorization") != "Bearer "+metricsToken {
			w.Header().Set("WWW-Authenticate", "Bearer")
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
		r.mu.Lock()
		defer r.mu.Unlock()
		w.Header().Set("Content-Type", "text/plain; version=0.0.4; charset=utf-8")
		fmt.Fprintf(w, "# HELP repomender_build_info Build information.\n# TYPE repomender_build_info gauge\nrepomender_build_info{version=\"%s\"} 1\n", r.build)
		fmt.Fprintln(w, "# HELP repomender_http_requests_total HTTP requests by route and status class.")
		fmt.Fprintln(w, "# TYPE repomender_http_requests_total counter")
		keys := make([]key, 0, len(r.requests))
		for item := range r.requests {
			keys = append(keys, item)
		}
		sort.Slice(keys, func(i, j int) bool {
			return strings.Join([]string{keys[i].method, keys[i].route, keys[i].status}, "\x00") <
				strings.Join([]string{keys[j].method, keys[j].route, keys[j].status}, "\x00")
		})
		for _, item := range keys {
			sample := r.requests[item]
			fmt.Fprintf(w, "repomender_http_requests_total{method=\"%s\",route=\"%s\",status_class=\"%s\"} %d\n",
				sanitizeLabel(item.method), sanitizeLabel(item.route), item.status, sample.count)
		}
		fmt.Fprintf(w, "# HELP repomender_rate_limit_rejections_total Requests rejected by the M10 rate limiter.\n# TYPE repomender_rate_limit_rejections_total counter\nrepomender_rate_limit_rejections_total %d\n", r.rateLimitRejected)
	})
}

type responseWriter struct {
	http.ResponseWriter
	status int
}

func (w *responseWriter) WriteHeader(status int) {
	if w.status != 0 {
		return
	}
	w.status = status
	w.ResponseWriter.WriteHeader(status)
}

func (w *responseWriter) Write(body []byte) (int, error) {
	if w.status == 0 {
		w.WriteHeader(http.StatusOK)
	}
	return w.ResponseWriter.Write(body)
}

func (w *responseWriter) Flush() {
	if w.status == 0 {
		w.WriteHeader(http.StatusOK)
	}
	if flusher, ok := w.ResponseWriter.(http.Flusher); ok {
		flusher.Flush()
	}
}

func (w *responseWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }

func normalizedPath(path string) string {
	if path == "" || path == "/" {
		return "/"
	}
	parts := strings.Split(strings.Trim(path, "/"), "/")
	for i, part := range parts {
		if looksLikeID(part) {
			parts[i] = ":id"
		}
	}
	return "/" + strings.Join(parts, "/")
}

func looksLikeID(value string) bool {
	if len(value) >= 32 && strings.Count(value, "-") >= 2 {
		return true
	}
	if len(value) >= 16 {
		for _, r := range value {
			if (r < '0' || r > '9') && (r < 'a' || r > 'f') && (r < 'A' || r > 'F') {
				return false
			}
		}
		return true
	}
	return false
}

func sanitizeLabel(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	value = strings.ReplaceAll(value, "\n", "")
	return value
}
